# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: postgresql
  database: aleprojectsdb
  encoding: utf8

test:
  adapter: postgresql
  database: aleprojectsdb_test
  encoding: utf8

cucumber:
  adapter: postgresql
  database: aleprojectsdb_cucumber
  encoding: utf8